### PR TITLE
Simple change to have the option to use UTC or LocalTime.

### PR DESCRIPTION
**Pull request by ezequielfalcon**
Hi! Sorry for modifying so many lines, arrenged a bit the identation.
I've added an option to the Initialize method to be able to choose UTF for de DateTime in the final Syslog message. If you agree you could add it to your branch!
Regards

### CODE REVIEW

**Comment by stormforce133** [comment]
Hi! Sorry for modifying so many lines, arrenged a bit the identation.
I've added an option to the Initialize method to be able to choose UTF for de DateTime in the final Syslog message. If you agree you could add it to your branch!
Regards

**Comment by JonCanning** [comment]
Thanks for that. Would you mind if I changed it to useLocal and have UTC as the default?

**Comment by ezequielfalcon** [comment]
No problem!

**Comment by JonCanning** [comment]
That's now in nuget, cheers!

**Pull request merged**
